### ISSUE TITLE
Links for translations aren't working

### ISSUE THREAD

**Issue by eduardonunesp** [loomnetwork/cryptozombie-lessons#107]
Some links on the course screen aren't working, maybe is because of some layer.

Page: https://cryptozombies.io/en/course/

Note: https://cl.ly/41470E0I410H

**Comment by mattkanwisher** [comment]
Links on homepage (upper right hand corner) goto the translated version of the lander page not the course

**Comment by eduardonunesp** [comment]
Yeh, exactly I said course because the url `en/course/`

**Comment by enlight** [comment]
Works for me, what browser & OS are you using? Anything in the console log?

**Comment by enlight** [comment]
Ah, I can reproduce it now. When the window is too narrow the language links that overlap the lesson menu banner "air space" can't be clicked on.
