### ISSUE TITLE
Not all code changes are saved

### ISSUE THREAD

**Issue by microbecode** [loomnetwork/cryptozombie-lessons#181]
Even if you finish a chapter succesfully and go to the next one the code changes are not always saved.
What I've noticed:
1) Complete lesson 5
2) Go back to the lesson at some point later (unsure if this would happen also right after completing the chapter)
3) Have a look at chapter 13 (which is the last one which shows the 'newest' codes)
4) Open zombieattack.sol
5) Look at function 'attack'. The incrementations are still with ++ even if you had previously replaced them with .add. The same problem manifests probably also elsewhere, but now noticed only this.

**Comment by hswopeams** [comment]
I'm having the same problem. My progress is saved (meaning every time I log in it takes me to the correct next lesson), but none of my code is saved. Whenever I look at a previous lesson, I see the "start here" text. Did you find a solution for this problem?

**Comment by microbecode** [comment]
Honestly, I did not look into it after that. So, no.

**Comment by hswopeams** [comment]
I posted to the Telegram group and got an answer from an admin. He said it's not meant to save the code between lessons.
