### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by gabrielgoodhelp** [loomnetwork/cryptozombie-lessons#185]
Ciao, I’d like to translate the course in Italian. Can I work on it? Is someone who’s already doing it and wants to join forces?

**Comment by monika-w** [comment]
I'd like to help as well!

**Comment by Chococoin** [comment]
Ciao!
Avete già cominciato la traduzione?

**Comment by monika-w** [comment]
Ciao! 
No, non ho ancora cominciato, perché l'italiano non è la mia prima lingua, ho voluto farlo se qualcuno aveva già iniziato e posso aiutare un po'. Ma posso iniziare se nessun altro lo fa.

**Comment by Chococoin** [comment]
Ho visto che già @mattkanwisher a cominciato le traduzioni ma non riesco a trovare il repositorio che contiene il lavoro già iniziato.

**Comment by nobady90** [comment]
I'm doing the Italian translation.
Made from scratch because I have not found anything about it.
