### ISSUE TITLE
ZombieAttack or ZombieBattle in Lesson 5, Chapter 1

### ISSUE THREAD

**Issue by Ander02** [loomnetwork/cryptozombie-lessons#200]
First a compliment for the incredible lessons, but there was an error in the first chapter of lesson 5, where our ZombieOwnership contract should inherit from ZombieAttack, but that does not exist, so the ZombieOwnership should inherit from ZombieBattle developed by every correct 4th lesson?

In short

    pragma solidity ^0.4.19;

    import "./zombieattack.sol";

    contract ZombieOwnership is ZombieAttack {

    }

should be 

    pragma solidity ^0.4.19;

    import "./zombieattack.sol";

    contract ZombieOwnership is ZombieBattle {

    }

**Comment by enlight** [comment]
Thank you for the bug report. We've fixed this issue and will be releasing an update shortly.
