### ISSUE TITLE
L1C8: Missed opportunity to talk about (saving) gas

### ISSUE THREAD

**Issue by willnwhite** [loomnetwork/cryptozombie-lessons#205]
> // create a New Person:
> `Person satoshi = Person(172, "Satoshi");`
> // Add that person to the Array:
`people.push(satoshi);`
> We can also combine these together and do them in one line of code to keep things clean:
> `people.push(Person(16, "Vitalik"));`

It's not just cleaner, but cheaper (less gas) to do it the second way.

**Comment by tesla809** [comment]
So we save gas here by not creating that extra variable and just instantiating and pushing into the array? I would say the above way is cleaner because its clearer. Given that there is an incentive to save gas, does Solidity encourage terse hard to read code?

**Comment by willnwhite** [comment]
> So we save gas here by not creating that extra variable and just instantiating and pushing into the array?

Yes.

> Given that there is an incentive to save gas, does Solidity encourage terse hard to read code?

In this case, the terser code is cheaper, and once you've understood what it does, cheaper is better. Comments can be used to explain terse code, e.g. `people.push(Person(16, "Vitalik")); // creates a new Person and adds that person to the array`.

I think it should say here: "We can also combine these together and do them in one line of code to keep things clean, and cheap:".
