### ISSUE TITLE
Lesson Six - Chapter 1 - HTML comments treated as bugs

### ISSUE THREAD

**Issue by roschler** [loomnetwork/cryptozombie-lessons#209]
Hi Loom Network,

Glad to see Lesson 6 released!  I'll be posting issues as I find them.

In Chapter 1 - if you don't delete the hint HTML comment:

It flags that line as an error.  I guess HTML comments are not being ignored by the parser?

**Comment by andreipope** [comment]
Thanks! It looks like the issue has been fixed so I'm closing this.
