### ISSUE TITLE
Lesson 6 - Chapter 8 - Answer Parser won't accept unit parameter in toWei call

### ISSUE THREAD

**Issue by roschler** [loomnetwork/cryptozombie-lessons#212]
Look at the screenshot below where I clicked on "Show Answer" to find out why the answer parser was not accepting my answer for Lesson 6, Chapter 8.  As you can see, the answer shows the _toWei()_ call _without_ "ether" as the second argument.  I'm assuming that "ether" is the default argument?  In any case, I believe most people will duplicate the _toWei()_ call shown in the lesson text like this:

```
CryptoZombies.methods.levelUp(zombieId)
.send({ from: userAccount, value: web3js.utils.toWei("0.001"**, "ether"**) })
```

And it looks like the answer parser won't accept it.  See below.

![image](https://user-images.githubusercontent.com/4660487/38212222-f9844082-368a-11e8-90e8-41950848770b.png)

**Comment by kokosabu** [comment]
#241

**Comment by andreipope** [comment]
Closing this at it has been fixed.
