### ISSUE TITLE
One really tiny typo in Lesson 6 - Chapter 3

### ISSUE THREAD

**Issue by roschler** [loomnetwork/cryptozombie-lessons#213]
In Chapter 3 there is this text:

"Lastly, let's instantiate our contract. Set cryptoZombies equal to an new ..." 

Should be: "a new"

That's all I found.

**Comment by andreipope** [comment]
@roschler Thanks! It is fixed in https://github.com/loomnetwork/cryptozombie-lessons/pull/639
