### ISSUE TITLE
PT lesson title is too long to fit on the lesson menu

### ISSUE THREAD

**Issue by enlight** [loomnetwork/cryptozombie-lessons#23]
![image](https://user-images.githubusercontent.com/233003/35436252-4a23eef6-02c0-11e8-962c-1b6f9cc5fc02.png)

@eduardonunesp can you use a shorter title in https://github.com/loomnetwork/cryptozombie-lessons/blob/master/pt/1/00-overview.md ?

**Comment by eduardonunesp** [comment]
@enlight sure I'll fix that

**Comment by enlight** [comment]
I believe this has been fixed.
