### ISSUE TITLE
Lesson 6 - Chapter 1 - script tags

### ISSUE THREAD

**Issue by doutori** [loomnetwork/cryptozombie-lessons#233]
Hi! Crypto Zombie Team.
The existing sample code in chapter 1 is like this.
```
<script language="javascript" type="text/javascript" src="web3.min.js"></script>
```

But, `language` attribute is deprecated in HTML5.
Also, as it is possible omit the `type` attribute too.
How about removing both?

```
<script src="web3.min.js"></script>
```

**Comment by eduardonunesp** [comment]
Hey @doutori thanks for the heads up, I'll check with the team about the updates 👍
