### ISSUE TITLE
Minor mistake in Lesson 4, Chapter 10

### ISSUE THREAD

**Issue by gabrocheleau** [loomnetwork/cryptozombie-lessons#254]
In the instructions, the following is written : 

> In chapter 6 we calculated a random number from 0 to 100. Now let's use that number to determine who wins the fight, and update our stats accordingly.

However, the random number generated is actually from 0 to 99 (since 100 % 100 returns 0). Therefore, the conditional in the function should be "less than" and no "less than or equal to", as the latter gives a 71% (0 to 70 vs 71 to 99) chance of winning to the attacker.

Thanks for the tutorials btw.

**Comment by MarekSefranek** [comment]
I just wanted to write the same issue before I found it was already here. Thx. But this is from 2018. Can this minor issue please be fixed? Should I provide a pull request?

Anyway, thanks for the tutorial, it was fun and informative.

**Comment by andreipope** [comment]
@gabrocheleau Thanks for taking the time to create this issue. I'm closing it for now and we'll review https://github.com/loomnetwork/cryptozombie-lessons/pull/477.
