### ISSUE TITLE
Polish translation.

### ISSUE THREAD

**Issue by pbrudny** [loomnetwork/cryptozombie-lessons#256]
Hi guys. Thanks for a great work you are doing!

I have seen that there is a polish translation in the repo (thanks to @piotr-galas) but it's not on the CryptoZombies.io yet.

Is there any more work required? If so I am willing to help.

**Comment by piotr-galas** [comment]
Translation required a lot of time. Recently I can not find any free time to improve translations. If you @pbrudny want to contribute, I can help you. I can e.g translate few files in your PR.

**Comment by pbrudny** [comment]
@piotr-galas Great that you started doing this translation 👍It really looks like a lot of work. I have quite a lot of free time right so I am going to focus on finishing that. It would be helpful if you could (from time to time) have a look in to my PRs even to verify and correct some typos.

**Comment by pbrudny** [comment]
@piotr-galas I mentioned polish translation on Telegram and got suggestion from @phDooY to use https://crowdin.com/project/cryptozombies instead. So I will move the changes there.

**Comment by piotr-galas** [comment]
Sure, It is better than github to translation.

**Comment by janforys** [comment]
Hi! Im able to help in translation too. How can I help? Maybe we will share some work?
