### ISSUE TITLE
Misleading instructions in Lesson 6, Chapter 8

### ISSUE THREAD

**Issue by gabrocheleau** [loomnetwork/cryptozombie-lessons#258]
In this chapter, we are instructed to make the user send 0.001 ether using the web3j.utils.toWei function. In the example, the "ether" argument is specified as such :

`web3js.utils.toWei("0.001", "ether")`

However, inputting this function as is in the exercise returns an error. The corrector actually seems to check for:

`web3js.utils.toWei("0.001")`

I'm aware that toWei defaults to ether, but perhaps the corrector could accept both?

Also, I did not find it clear that the following had to be included:

```
.on("error", function(error) {
          $("#txStatus").text(error);
        });        
```

since there is not mention of it in the instructions. Maybe this should be specified?

**Comment by markszabo** [comment]
Same issue as #212 and solved in a pending PR #241

**Comment by togtalk** [comment]
nice but am waitinf to find urgent deposit

**Comment by andreipope** [comment]
Closing this as #241 has already been merged.
