### ISSUE TITLE
Typo of capitalised parameter when calling function

### ISSUE THREAD

**Issue by eskp** [loomnetwork/cryptozombie-lessons#260]
In Chapter 7: Sending Transactions, a call to `feedOnKitty()` for some reason expecting one of the argumets `kittyId` to be capitalised:
`return CryptoZombies.methods.feedOnKitty(zombieId, KittyId)`
Should be lower case.

**Comment by KorbinianK** [comment]
Fix: #263

**Comment by eskp** [comment]
Thanks @KorbinianK

**Comment by KorbinianK** [comment]
Why did this get closed? The pull request is still open for review. Every potentially new translation will include these typos.

**Comment by eskp** [comment]
True @KorbinianK, I jumped the gun.

**Comment by andreipope** [comment]
Closing this as the issue has been fixed.
