### ISSUE TITLE
Adding a semicolon at the end of a line is invalid JavaScript code

### ISSUE THREAD

**Issue by MiLeung** [loomnetwork/cryptozombie-lessons#265]
<img width="1440" alt="screen shot 2018-05-12 at 1 58 40 pm" src="https://user-images.githubusercontent.com/9166324/39961579-2ac9bc8a-55ee-11e8-9025-80b73e944004.png">

**Comment by morenoh149** [comment]
I'd assume that the solidity parser is being used on the javascript. Solidity does not do automatic semicolon insertion. So you are correct, the semicolons aren't required in the html files.

**Comment by finite2** [comment]
I think it would really help if you stripped semicolons from all the solutions prior to checking the solution for the js files

**Comment by morenoh149** [comment]
yeah, or if they are using regex just `;?`

**Comment by andreipope** [comment]
@MiLeung Thanks for taking the time to create this pull request. Note that semicolons are optional in JS. I'm closing this as it's not an issue.
