### ISSUE TITLE
wrong version of web3.min.js.

### ISSUE THREAD

**Issue by zoeleesss** [loomnetwork/cryptozombie-lessons#283]
I tried to use the code in the cryptozombies lessons Chapter 6 and use the web3.min.js (api version 0.20.3). But it's always wrong, even the code to initialize a contract is wrong. 
I had to use 
`new web3.eth.contract(coreABI).at(address);` 
It's right, but when i tried to call a function in solidity , it's wrong again. 
There is a state variable (public string) called symbol in my contract. So i tried to get the value of it via
`contract.symbol.call()` 
It says 
`inpage.js: 1 Uncaught TypeError: this._eth.call is not a function`
So, i dont know if it's the problem of the API version or something.
I used a CDN version of web3.min.js which is 
`<script src="https://cdn.jsdelivr.net/gh/ethereum/web3.js/dist/web3.min.js"></script>`

I want to ask you guys where you can find a good web3.min.js which can use the style in the Chapter 6 lesson. like 
`new web3js.eth.Contract(coreABI,address);`

Can you simply share the right file, please? Thanks in advance!! 🥇 👍 👍

**Comment by andreipope** [comment]
Fixed in https://github.com/loomnetwork/cryptozombie-lessons/pull/615
