### ISSUE TITLE
Lesson 5 Chapter 8 Answer Validation Enhancement? 

### ISSUE THREAD

**Issue by knd** [loomnetwork/cryptozombie-lessons#284]
Link: https://cryptozombies.io/en/lesson/5/chapter/8

Are the 2 statements equivalent? 

![image](https://user-images.githubusercontent.com/1356620/41189129-272dfe68-6bf3-11e8-9be6-1d7fa688d0b0.png)

**Comment by rotcivegaf** [comment]
Yes, its the same but in other order

**Comment by finite2** [comment]
It can't be that hard to have multiple correct solutions can it?

**Comment by andreipope** [comment]
Our parser is pretty basic, and it won't consider the answer correct unless you're using the same order.
