### ISSUE TITLE
Events should use emit

### ISSUE THREAD

**Issue by morenoh149** [loomnetwork/cryptozombie-lessons#285]
Recent versions of solidity use the `emit` keyword to invoke an Event.

https://solidity.readthedocs.io/en/v0.4.24/structure-of-a-contract.html?highlight=event#events

lessons like https://cryptozombies.io/en/lesson/5/chapter/5 should be updated to use the new syntax as devs may mistakenly use the documentation to try to solve the problem.

**Comment by andreipope** [comment]
Thanks! I'm closing this as it has already been fixed.
