### ISSUE TITLE
Lesson 6- Chapter 8, which answer should I follow?

### ISSUE THREAD

**Issue by moskva** [loomnetwork/cryptozombie-lessons#291]
My answer followed this code given in the instruction.
![image](https://user-images.githubusercontent.com/1446952/41444562-67e54498-7076-11e8-8cab-692664ba6f4a.png)

But the official answer says it's wrong.
![image](https://user-images.githubusercontent.com/1446952/41444557-61205724-7076-11e8-9ce0-12052c5d544d.png)

**Comment by andreipope** [comment]
Closing this issue as it works as expected.
