### ISSUE TITLE
A question about approval

### ISSUE THREAD

**Issue by CNSumi** [loomnetwork/cryptozombie-lessons#306]
First of all, thank you very much for your course, it has really helped me a lot.
in https://cryptozombies.io/zh/lesson/5/chapter/8
if i approval a token to another, but i can transfer it before another take it, is it expected?

**Comment by dapplion** [comment]
Depends in the exact token implementation. This very specific implementation of the ERC721 is very basic and has security holes like the one you found. 
You could approve a token to yourself, sell it to some else, and then use the approve functionality to claim the ownership back to you.

Check this reference implementation for an actual full fledged implementation of the ERC721 standard https://github.com/0xcert/ethereum-erc721/blob/master/src/contracts/tokens/nf-token.sol

**Comment by dapplion** [comment]
On the implementation I mentioned, the approval field is cleared when the token is transfered, preventing the situation you expose on your question.

```solidity
function _transfer(address _to, uint256 _tokenId) internal {
    address from = idToOwner[_tokenId];
    _clearApproval(_tokenId); // <<<< Here <<<<
    _removeNFToken(from, _tokenId);
    _addNFToken(_to, _tokenId);
    emit Transfer(from, _to, _tokenId);
}
```

https://github.com/0xcert/ethereum-erc721/blob/e3d101d54138ac3df006b341be7b14712cabadc3/src/contracts/tokens/nf-token.sol#L329
