### ISSUE TITLE
Chapter 2 Lesson 14 - One zombie/kitty combination dna is wrong

### ISSUE THREAD

**Issue by chiptus** [loomnetwork/cryptozombie-lessons#353]
When clicking the middle kitty I get a combination dna that doesn't end with 99:
![screenshot from 2018-10-12 18-03-48](https://user-images.githubusercontent.com/1381655/46877312-390eb600-ce49-11e8-9c19-8fcd5b58d649.png)

**Comment by andreipope** [comment]
I don't understand the issue here. I'm closing this but feel free to create a new issue, making sure you provide more details.
