### ISSUE TITLE
“start here”翻译成了“事件”

### ISSUE THREAD

**Issue by freewind** [loomnetwork/cryptozombie-lessons#359]
https://cryptozombies.io/en/lesson/1/chapter/12

![image](https://user-images.githubusercontent.com/333781/47854752-84e7c600-de1d-11e8-88cf-f1669d366023.png)

![image](https://user-images.githubusercontent.com/333781/47854761-8f09c480-de1d-11e8-8e69-b692484571c3.png)

**Comment by HangYang** [comment]
thx, fixed with https://github.com/loomnetwork/cryptozombie-lessons/commit/ee9b7246fe333e4728715dc98401a230a7cb3d22
