### ISSUE TITLE
Progress not saved and next chapter button not working

### ISSUE THREAD

**Issue by seanputera** [loomnetwork/cryptozombie-lessons#384]
I logged out and logged in back to my account using GitHub, it seems that my progress is reset. Also, when i clicked the 'next chapter' button at the bottom right, it doesn't do anything. I have to go back to the main curriculum page and click again. Also, if you go back to the main curriculum page AGAIN and click into the chapter, it will go to the next chapter without completing the previous one!

**Comment by HangYang** [comment]
thx, fixed
