### ISSUE TITLE
Lesson 9 chapter 6

### ISSUE THREAD

**Issue by Oxyaction** [loomnetwork/cryptozombie-lessons#386]
First step:
> Create an if statement that checks if `individualSupply[_tokenId]` is greater than 0.  
> If this condition is true, that means this token is a Limited Edition card with a fixed supply.

Why here should we use `individualSupply[_tokenId]`? Suppose it should be  `individualSupply(_tokenId)` since there is a method `individualSupply` and not the state variable.

**Comment by HangYang** [comment]
fxied, thx
