### ISSUE TITLE
Testcases failed for 0.4.25

### ISSUE THREAD

**Issue by cmaliwal** [loomnetwork/cryptozombie-lessons#395]
Hi,

https://cryptozombies.io/en/lesson/7/chapter/3
In above mention chapter testcases failed for 0.4.25.

when I try with 0.4.25 compiler gives error and when I change version ( 0.4.24) its success
and on the next chapter it again change the version 0.4.25

![screenshot from 2019-02-11 18-32-29](https://user-images.githubusercontent.com/21885663/52565103-e27fab80-2e2b-11e9-8d31-ccd7d8e768cf.png)

![screenshot from 2019-02-11 18-32-32](https://user-images.githubusercontent.com/21885663/52565124-f0353100-2e2b-11e9-81ab-237e218e60c1.png)

**Comment by andreipope** [comment]
Closing this issue as we've upgraded the version of Solidity.
