### ISSUE TITLE
Making the Zombie Library, Chapter 13 Solution Issue

### ISSUE THREAD

**Issue by ydax** [loomnetwork/cryptozombie-lessons#398]
Hi friends. The solution [in your medium post](https://medium.com/bitfwd/solidity-fundamentals-cryptozombies-lesson-one-and-two-64ccd2631cef) seems to be missing an emit before firing the NewZombie event. 
<img width="706" alt="chapter 2 13 detail" src="https://user-images.githubusercontent.com/13105985/53302267-56558700-3822-11e9-986f-0cc23b490cb8.png">

Also, it was declaring a variable whilst also pushing to an array was confusing. I would have thought that we would have needed to run the push and the variable declaration on two separate lines and this wasn't covered in the previous lessons.

**Comment by pdavisjones** [comment]
<img width="668" alt="syntax issue" src="https://user-images.githubusercontent.com/13105985/53530604-99775a80-3aad-11e9-9172-1ccf43cec7f4.png">

**Comment by andreipope** [comment]
@ydax Thanks! I'm closing this issue as it has already been fixed.
