### ISSUE TITLE
mix a function name and mapping name in Lesson 9

### ISSUE THREAD

**Issue by quantumcatwang** [loomnetwork/cryptozombie-lessons#401]
In the CryptoZombie Lesson 9, the contract `ZombieCard.sol`, we have declared a `mapping` to store the total supply:
```
mapping(uint => uint) internal tokenIdToIndividualSupply;
```
and a function to view this supply:
```
function individualSupply(uint _tokenId) public view returns (uint);
```

However, in the function `awardToken(uint _tokenId, address _to, uint _amount)`, the second line is:
```
if (individualSupply[_tokenId] > 0)
```
which is wrong. `individualSupply` is the function name not the mapping name. The correct way is:
```
if (individualSupply(_tokenId) > 0)
```

I fix it for all files and all language version in a new pull request

**Comment by andreipope** [comment]
@quantumcatwang Good catch. Thanks!
