### ISSUE TITLE
cn translation errors

### ISSUE THREAD

**Issue by aeieli** [loomnetwork/cryptozombie-lessons#423]
hi, I found a translation error in zh/lesson/3/chapter/6 :

"接下来，创建一个名为 _isReady 的函数。这个函数的参数也是名为 _zombie 的 Zombie storage。这个功能只具有 internal 可见性，并返回一个 bool 值。"

In fact, [只具有 internal 可见性] must be => [只具有 internal 可见性,  view 只读属性]

The missing of 'view' attribute requirements will lead Chinese users to misunderstand the title requirements and make wrong answers.

**Comment by HangYang** [comment]
多谢。英文课程在翻译后应该更新过，中文没有同步过来。欢迎提交PR修改。
