### ISSUE TITLE
 Lesson 7 Chapter 3 has error in checking answer. Tries to correct pragma 0.4.25 to 0.4.24, other chapters use 0.4.25

### ISSUE THREAD

**Issue by oo-00** [loomnetwork/cryptozombie-lessons#426]
As said in the description, Lesson 7 Chapter 3 incorrectly catches the pragma version as an error, inconsistent with the rest of the lesson.

**Comment by andreipope** [comment]
@oo-00 Thanks for taking the time to open this issue! Please feel free to create a PR against this repo, and we'll be happy to review and merge it.
