### ISSUE TITLE
PT translation errors

### ISSUE THREAD

**Issue by vitumenezes** [loomnetwork/cryptozombie-lessons#431]
Hi! I am a Brazilian student of information technology.

During the tutorial I found an error in the translation.

> Como você pode ver, usarmos a palavra reservada private após o nome da função.

The correct would be:

> Como você pode ver, usamos a palavra reservada private após o nome da função.

The error is in the verb "usarmos".

**Comment by vitumenezes** [comment]
#432

**Comment by vitumenezes** [comment]
In part 1, in events.md the variable "zombieID" is wrong. If written this way, an error occurs. The correct one is "zombieId", as in the other translations.

I do not know, but probably this error may also exist in another translation.

**Comment by HangYang** [comment]
thx, your PR been merged by PR #432
