### ISSUE TITLE
Why you people do not save state if a user has logged via registered Email Id or Github and Why No Feature of exporting to Github post lesson completion.

### ISSUE THREAD

**Issue by singhrajgithub** [loomnetwork/cryptozombie-lessons#433]
Hi,

My query is if I am going through https://cryptozombies.io/en/lesson/1 and let's suppose i am in mid of some lesson and i have to stop from there and later I want to continue it from. can i do that ?

And one more thing if I have logged in via GitHub why am I not able to export or add those answers directly to Github? 

Are you guys working on it , if not then please start as i wanted to export my answer to my Github post lesson completion on cryptoZombies.

**Comment by HangYang** [comment]
we ARE saving state/learning progress. once you logged in, any progress will be saved. 
here is my progress  as sample
<img width="1095" alt="Screen Shot 2019-12-11 at 12 27 17 PM" src="https://user-images.githubusercontent.com/3389447/70591574-951dc780-1c11-11ea-8429-b22724dcb572.png">

**Comment by singhrajgithub** [comment]
@HangYang thanks for responding. There were some issues earlier with my profile due to which state was not getting saved. Now I am able to see it.
