### ISSUE TITLE
Lesson 11 chapter 11 doesn't test for unauthorized transfers

### ISSUE THREAD

**Issue by zimmah** [loomnetwork/cryptozombie-lessons#449]
There is no test case for any unauthorized person trying to make a transfer, which seems like something really serious to miss and should be tested for.

Imagine if you accidentally make a contract where anyone can just transfer anything.

**Comment by andreipope** [comment]
Hey @zimmah, this is a tutorial, and we cannot cover all scenarios. If you feel inclined to improve the lessons, please create a PR. We would love to review it🙌🏻.
