### ISSUE TITLE
zombienattack.sol spanish contract declaration

### ISSUE THREAD

**Issue by DanielMartinezFernandez** [loomnetwork/cryptozombie-lessons#454]
In English contras is:
contract ZombieAttack is ZombieHelper {

In Spanish:
contract **ZombieBattle** is ZombieHelper {

In Lesson 3, Chapter 3, I didn't understand who is calling ZombieAttack if the contract name is ZombieBattle. When I looked at it in English, I found the error.

![attackEs](https://user-images.githubusercontent.com/31846613/102200683-748fe980-3ec5-11eb-8005-a1475b22c607.jpg)
![attackEn](https://user-images.githubusercontent.com/31846613/102200813-9ab58980-3ec5-11eb-8564-211154a66ad6.jpg)

**Comment by andreipope** [comment]
@DanielMartinezFernandez Thanks for taking the time to create this issue. Feel free to file a PR, and we'll be happy to review it.
