### ISSUE TITLE
French translation - lesson 03 - grammar and typo fixes

### ISSUE THREAD

**Issue by gryzor2** [loomnetwork/cryptozombie-lessons#458]
Hi,

I am a french native, and I'm happy to contribute some fixes to the french translation of lesson 3.
Only grammar and typos ; I have made no change in the structure or content.

[chap03-french-grammar-and-typo-fixes.patch.txt](https://github.com/loomnetwork/cryptozombie-lessons/files/5756749/chap03-french-grammar-and-typo-fixes.patch.txt)

I would be happy to commit changes into a branch and request MRs, but I cannot seem to be able to create a branch here.

Therefore, patch attached.

Cheers,

Vincent

**Comment by gryzor2** [comment]
Additionnally, here is a patch for lesson 4. Same principles ^^

Cheers,

Vincent
[chap04-french-grammar-and-typo-fixes.patch.txt](https://github.com/loomnetwork/cryptozombie-lessons/files/5758096/chap04-french-grammar-and-typo-fixes.patch.txt)

**Comment by gryzor2** [comment]
Additionnally, here is a path for lesson 5.

Cheers,

Vincent
[chap05-french-grammar-and-typo-fixes.patch.txt](https://github.com/loomnetwork/cryptozombie-lessons/files/5760611/chap05-french-grammar-and-typo-fixes.patch.txt)

**Comment by andreipope** [comment]
@gryzor2 We would be happy to improve the French translation. That being said, this is a public repo meaning that you can fork it and create a branch.
