### ISSUE TITLE
French translation : git master is not sync with website

### ISSUE THREAD

**Issue by gryzor2** [loomnetwork/cryptozombie-lessons#460]
Hi,

I am finding typos and grammar french errors in lesson 5, on the website (eg : https://cryptozombies.io/fr/lesson/5/chapter/3 ), but many of them have already been fixed in the master branch.

Can you sync ?

Cheers,

Vincent

**Comment by andreipope** [comment]
@gryzor2 @G-Guillard Thanks for providing this feedback! We're aware that it could take some time for changes to be visible on the website, and we're working on improving the process.
