### ISSUE TITLE
Typo in lesson 16 chapter 6

### ISSUE THREAD

**Issue by AireshBhat** [loomnetwork/cryptozombie-lessons#491]
Before anything, I would really like to thank everyone involved in developing this 🙌. This has helped me learn a lot and given me a lot of confidence 💯 . Thank you 😀

While initialising a struct, the lesson adds a new keyword before the struct which shouldn't be there.
Below are the actual lines from the lesson

Then, you can instantiate MyStruct like so:
```
  MyStruct memory myStructInstance; // declare the struct
  myStructInstance = new MyStruct(msg.sender, 200); // initialize it 
```

The last line there should not be `new MyStruct(msg.sender, 200);` rather it should be just `MyStruct(msg.sender, 200)`;

The linter picks this up though!

Thank you once again! Good day!

**Comment by andreipope** [comment]
@AireshBhat Thanks! I'm closing this issue as the pull request has already been merged.
