### ISSUE TITLE
Chapter 11 Lesson 14 

### ISSUE THREAD

**Issue by EbrahimElbagory** [loomnetwork/cryptozombie-lessons#507]
https://cryptozombies.io/en/lesson/14/chapter/11

Your code corrects my code because you miss spelled Contract in CallerContractInterface
`   CallerContracInterface callerContractInstance;
    callerContractInstance = CallerContracInterface(_callerAddress);
`

**Comment by andreipope** [comment]
@EbrahimElbagory @keeran Thank you. We merged the PR and will update the lessons soon.
