### ISSUE TITLE
Chapter 11 stuck on next chapter

### ISSUE THREAD

**Issue by andywong418** [loomnetwork/cryptozombie-lessons#508]
Whenever I try to click next chapter it gets stuck on this screen. Also tried to skip lesson to https://cryptozombies.io/en/lesson/11/chapter/8 but it just redirects back to https://cryptozombies.io/en/lesson/11/chapter/7.
<img width="1423" alt="Screenshot 2021-06-21 at 12 18 08" src="https://user-images.githubusercontent.com/6445805/122794980-aff2e280-d271-11eb-9b9b-68e576f37a4f.png">

**Comment by fibretothepremises** [comment]
Same. It's happened to me in 4: Zombie Battle System and 5: ERC721 & Crypto-Collectibles. Didn't have an issue in courses 1,2 & 3.

The issue is I cannot progress to the next lesson without exiting this page and re-navigating to it from the list of all courses.

**Comment by andreipope** [comment]
Hey, please disable any extensions that might interfere with JavaScript, or log out and log in again.
