### ISSUE TITLE
Lesson 4 chapter 1 Issues

### ISSUE THREAD

**Issue by eduardonunesp** [loomnetwork/cryptozombie-lessons#52]
Just few text issues, below:

But in Ethereum, because both the money (Ether), the data (transaction payload), and the contract code itself all live on Ethereum, it's possible `for for` you to call a function and pay money to the contract at the same time.

Let's say our game has a feature where users can pay ETH to level up their zombies. The ETH `wil` get stored in the contract, which you own — this a simple example of how you could make money on your games!

The function should first require that msg.value `is (are)` equal to levelUpFee.

**Comment by enlight** [comment]
Thanks for the bug report, can you mention which lesson & chapter this is in?

**Comment by enlight** [comment]
Thanks! I've fixed the issues you've mentioned.
