### ISSUE TITLE
Lesson 15 error

### ISSUE THREAD

**Issue by patr1cketh** [loomnetwork/cryptozombie-lessons#524]
![image](https://user-images.githubusercontent.com/87179170/126364712-fb037143-acbe-4d59-abe1-b0362e131243.png)
I don't understand why using semi-colons is wrong?

**Comment by dlsso** [comment]
It's not wrong, but the code checker requires an exact match, and this follows the convention in the rest of the lessons.

Recommend this issue be closed.
