### ISSUE TITLE
Lesson 15 chapter 2 error

### ISSUE THREAD

**Issue by patr1cketh** [loomnetwork/cryptozombie-lessons#525]
![image](https://user-images.githubusercontent.com/87179170/126371087-e74bdb44-9888-40fb-8205-bdb984793fd7.png)
SetLatestEthPriceEvent should be GetLatestEthPriceEvent

**Comment by andreipope** [comment]
Sorry but I don't understand this. Anyway, feel free to create a pull request and we'll review it.
