### ISSUE TITLE
Lesson 5 does not increment on completion

### ISSUE THREAD

**Issue by jjones2000** [loomnetwork/cryptozombie-lessons#535]
Once a chapter has been completed on Lesson 5, the page does not change to the next chapter automatically like previous ones.
Even clicking next or the completion notification does not work. 

However, changing the url to the next chapter number does work.

**Comment by code7777** [comment]
I'm having this issue as well.

**Comment by G-Guillard** [comment]
IIRC this issue appears on chapter 4 and above, chapters 1-3 are not affected.
