### ISSUE TITLE
Lesson 5: Lesson Complete (next chapter/lesson button doesn't show)

### ISSUE THREAD

**Issue by hurricanenara** [loomnetwork/cryptozombie-lessons#539]
<img width="1903" alt="Screen Shot 2021-08-23 at 8 43 17 PM" src="https://user-images.githubusercontent.com/58568960/130537705-18b7c6e5-8adf-4379-880f-4be942dbd4d0.png">

**Comment by 0xdx-xb** [comment]
Verified bug.

OS: macOS 11.6
Browser: Chrome 96.0.4664.110
