### ISSUE TITLE
Lesson 13: All about Binance chain, Chapter 1: Settings Things Up. Link Binance tesenet faucet 404

### ISSUE THREAD

**Issue by Oeufhp** [loomnetwork/cryptozombie-lessons#550]
In Lesson 13 Chapter link for [Binance testnet fauct](https://www.binance.com/en/dex/testnet/address) is showing 404

**Comment by andreipope** [comment]
@Oeufhp Thanks for taking the time to point this out. Unfortunately, the Binance chain is no longer maintained, so we decided to remove this lesson. The issue will be closed.
