### ISSUE TITLE
The course is not up to date with the repo on l. 14 ch. 10

### ISSUE THREAD

**Issue by bio-howard** [loomnetwork/cryptozombie-lessons#554]
https://github.com/loomnetwork/cryptozombie-lessons/blob/dfdab8062a802e5ad1f8f5daef1c3511367d1599/en/14/10.md

https://cryptozombies.io/en/lesson/14/chapter/10

From the repo: 
> Put It to the Test
> 
> Create a public function named setLatestEthPrice. It should take three parameters: _ethPrice (a uint256), _callerAddress (an address), and _id (a uint256). Don't forget to make it so that only the owner could call it.

On the website:

> Put It to the Test
> Create a public function named setLatestEthPrice. It should take three parameters: _ethPrice (a uint256), callerAddress (an address), and id (a uint256). Don't forget to make it so that only the owner could call it.

(missing underscores)

**Comment by andreipope** [comment]
Thanks for taking the time to provide this feedback. We're doing our best to publish the fixes asap, but sometimes it could take more time.
