### ISSUE TITLE
Zombie Battle System Chapter 4:  internal function randMod not prefixed with underscore "_"

### ISSUE THREAD

**Issue by BerberBerthold** [loomnetwork/cryptozombie-lessons#557]
Title explains itself.  By convention (as described by the cryptozombie lessons), internal functions should be prefixed with an underscore, so in Zombie Battle System Chapter 4, it should be `_randMod` and not `randMod`. right?

sorry if i misunderstood something.

**Comment by andreipope** [comment]
@BerberBerthold Thanks for taking the time to create this pull request. It's an `internal` function. Only `private` functions are prefixed with an underscore.

**Comment by zmberber** [comment]
oof i am sorry, even though i spent some time on thinking about making an issue, i was clearly not the most alert person...

thanks for the response!
