### ISSUE TITLE
Lesson 5: Chapter 12: SafeMath should be implemented in ZombieAttack but isn't.

### ISSUE THREAD

**Issue by vannieuwenhovej** [loomnetwork/cryptozombie-lessons#561]
In Chapter 12 of Lesson 5 the user has to protect zombieattack.sol from over- and underflows in Solidity using SafeMath.

zombieownership. sol inherits from zombieattack and ERC721 and implements SafeMath:
`contract ZombieOwnership is ZombieAttack, ERC721 {
  using SafeMath for uint256;
}`

and zombieattack.sol from inherits from zombiehelper without implementing SafeMath:
` contract ZombieAttack is ZombieHelper {
}`

zombieattack doesn't inherit from zombieownership neither explicitly or implicitly. There's no way it can access the library.
The assignment doesn't tell the user to also be `using SafeMath` in ZombieAttack.

Or am I really missing something here?

**Comment by 0xdx-xb** [comment]
Library implementation [changed](https://docs.soliditylang.org/en/latest/070-breaking-changes.html#functions-and-events) in solidity 0.7.0, so the implementation would be valid as is given `pragma solidity >=0.5.0 <0.6.0;` in use.

**Comment by andreipope** [comment]
@vannieuwenhovej Thank you for taking the time to point this out. As @0xdx-xb explained, this works as expected. I'll close the issue and keep this in mind for when we'll update the version of Solidity.
