### ISSUE TITLE
`toNumber()` isn't explained in Lesson 11 Chapter 9

### ISSUE THREAD

**Issue by BerberBerthold** [loomnetwork/cryptozombie-lessons#563]
In chapter 9 of Lesson 11, We read `zombieId` from the emitted Event.  But that already is a uint in solidity, so I was guessing it should be fine.  It is not immediately clear that `toNumber()` has to be applied.  Furthermore, I don't even know where `toNumber()` is defined, as it doesn't exist in javascript, but there does exist a ECMAScript specification for it.  When does `toNumber()` have to be used?  I see it in the Truffle docs as well, but I don't really get when it is necessary, and when not.  Do I use it whenever I call anything from a contract in solidity that is supposed to be a number (integer) of some kind?

**Comment by andreipope** [comment]
The front-end receives strings, you must call the `toNumber()` function to convert them to integers.
