### ISSUE TITLE
Suggested edits for Lesson 1 Chapter 8

### ISSUE THREAD

**Issue by bobtista** [loomnetwork/cryptozombie-lessons#603]
I've been sharing CryptoZombies with friends and several of them have gotten confused/stuck on this lesson in particular. One of them suggested these edits, and I thought it would be cool to walk her through contributing to an open source project and see if her suggestions get added :) 

If I can get permissions, I've got a branch ready that I could make a Pull Request for. Otherwise, the changes are as follows:
```

-people.push(Person(16, "Vitalik"));
+people.push(Person(172, "Satoshi"));
+```
+
+If we wanted to be able to create a new person with any given age and name, we could write a function like so:
+
+```
+// create and add a person to the people array
+function createPerson (uint _age, string memory _name) public {
+  // we can use the age and name given in the function arguments
+  people.push(Person(_age, _name));
+}

```
Make examples more consistent, add a sample createX function that uses given function arguments

**Comment by dlsso** [comment]
I think you're supposed to just submit the pull request so the maintainer can review.

**Comment by andreipope** [comment]
@bobtista Thanks for taking the time to create this issue. Feel free to file a pull request, and we'll be happy to review it.

**Comment by bobtista** [comment]
@andreipope I tried, but it seems I don't have permissions? 
`git push origin bobbyb/melissas-edits
ERROR: Permission to loomnetwork/cryptozombie-lessons.git denied to bobtista.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

and here's my git remote -v `
origin	git@github.com:loomnetwork/cryptozombie-lessons.git (fetch)
origin	git@github.com:loomnetwork/cryptozombie-lessons.git (push)`

Can you help? Do I need my ssh key added as a contributor or something?
