### ISSUE TITLE
Next Chapter Button doesn't work

### ISSUE THREAD

**Issue by creaturemonster** [loomnetwork/cryptozombie-lessons#628]
I am stuck on the 'Victory' page and I am not able to move on to the next chapter. 
![JSError](https://user-images.githubusercontent.com/11894266/155191450-124f8c72-b8d6-49d2-98a7-0f7eaff9f616.JPG)

**Comment by andreipope** [comment]
Hey, please disable any extensions that might interfere with JavaScript, or log out and log in again
