### ISSUE TITLE
 Typo in korean translation

### ISSUE THREAD

**Issue by thyoondev** [loomnetwork/cryptozombie-lessons#631]
Before anything, I would really like to thank everyone involved in developing this 🙌. This has helped me learn a lot and given me a lot of confidence 💯 . Thank you 😀

I found a translation error in ko/lesson/6/chapter/3 

"2. `<body>`의 `<script>` 태그 시작 부분에서, `cryptoZombies`라는 이름으로 `var`를 선언하고 어떤 값도 아직 핟당은 하지 말게. 추후 이 변수를 우리의 인스턴스화된 컨트랙트를 저장하는 데에 사용할 것이네."

"핟당" -> "할당"

Typos can confuse Koreans..😂 
Thank you once again! Good day!

**Comment by andreipope** [comment]
Hey @thyoondev , thank you for taking the time to fix these types. I've merged your PRs and the changes will be visible soon.

**Comment by thyoondev** [comment]
thank you! @andreipope , I'm glad I could help you😀😆 I will continue work for correct translation💪
