### ISSUE TITLE
Lesson 4 Chapter 11 _triggerCooldown triggers twice

### ISSUE THREAD

**Issue by phDooY** [loomnetwork/cryptozombie-lessons#67]
As noticed by our attentive user:

![image](https://user-images.githubusercontent.com/6223779/35793057-1c75c652-0a61-11e8-9b1d-c581c5873926.png)

**Comment by enlight** [comment]
I believe this was fixed in https://github.com/loomnetwork/cryptozombie-lessons/pull/126
