### ISSUE TITLE
I desire to contribute with translations to Spanish.

### ISSUE THREAD

**Issue by vacilagodzila** [loomnetwork/cryptozombie-lessons#90]
Hello, hope this message finds you well. 

I saw the instructions on the README file about creating a new branch to add a new lenguage. Just wanted to make sure this repo would also welcome spanish translation, if so I'll be glad to help.

Thank you!

**Comment by JSabio** [comment]
I think so,

We are a bunch of Spanish speakers on their TG group. I´m doing this translation by myself if you want some collab.

**Comment by vacilagodzila** [comment]
Hello, @JSabio . How can we get in touch to start translating? my TG alias is @scci96
