### ISSUE TITLE
Request for Spanish translation

### ISSUE THREAD

**Issue by nanik94** [loomnetwork/cryptozombie-lessons#92]
Hi!, can I translate this project into spanish ?

**Comment by JuanitoH29** [comment]
Yes, you are

**Comment by JuanitoH29** [comment]
Yes, you can*

**Comment by JSabio** [comment]
I´m translating the project to Spanish right now. Lesson 1 and 2 done already.

If you want, contact me for collab.

**Comment by JuanitoH29** [comment]
Hi! I'm in charge of the translations of the lessons into Spanish, could
you do thr pull request of lesson 1? Find me in thr telegram group I'm part
of the team @anuJuan

Thanks for reading

**Comment by JSabio** [comment]
I've made the PR of root files and first 2 lessons
